spring.datasource.url=jdbc:postgresql://localhost:5432/maestrocoach
spring.datasource.username=maestro
spring.datasource.password=maestro

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true